extends:
  - shared/storage.yml

name: mssql-full

triggers:
  - type: mssql
    host: "windows-host"
    username: "backup_user"
    password: "SECRET"
    output_dir_windows: "D:\\Backups\\backuppy"
    databases:
      - { name: AppDB,   backup_type: FULL }
      - { name: OtherDB, backup_type: FULL }
    compression: true
    checksum: true

sources:
  - type: files
    paths: ["/mnt/win-server1/backuppy/*-full-*.bak"]
    delete_after_pickup: false

compression:
  method: zstd
  level: 10

local:
  enabled: true
  path: /var/backups/backuppy/mssql-full
  keep_last: 7

webdav:
  remote_path: "Backups/mssql-full"
  keep_last: 14
