extends:
  - shared/storage.yml

name: postgres-app

triggers:
  - type: postgres
    host: localhost
    username: postgres
    output_dir: /tmp/backuppy-postgres-app
    databases: [appdb]

sources:
  - type: files
    paths: ["/tmp/backuppy-postgres-app/*"]
    delete_after_pickup: true

compression:
  method: zstd

local:
  enabled: true
  path: /var/backups/backuppy/postgres-app
  keep_last: 7

webdav:
  remote_path: "Backups/postgres-app"
